### PR TITLE
add build config + keys

### PR DESCRIPTION
**Pull request by ryelo**

### CODE REVIEW

**Comment by ryelo** [comment]
I don't know why the `continuous-integration/travis-ci/pr` is still showing up, you can ignore that one.

**Comment by joeldmyers** [comment]
LGTM; @patrickeasters if you can just review the travis part it would be helpful. Thanks!

**Review by joeldmyers — APPROVED** [review]

**Comment by zanewoodfin** [comment]
Reminder: we need to push our up to date code out to this repo from gitlab before merging anything.

**Comment by zanewoodfin** [comment]
@ryelo I just pushed up our most recent code to branch `main` and changed that to be our primary branch.  Could you rebase this pull request to that new branch?

**Comment by ryelo** [comment]
Yep!

**Pull request closed without merging**
