### PR TITLE
Teamnado 3919 to main-stable - Update Spacing 

### PR DESCRIPTION
**Pull request by BrooklynLCodes**

### CODE REVIEW

**Comment by jlgre** [comment]
Was this branched off of main? I am seeing commits in the log that are only present in main (ex. 15abe594f20b1887eaa4c3b7383da21087b7c052)

**Comment by jlgre** [comment]
Per offline discussion this _was_ branched off of main - but it should be fine to continue through the process. My concerns (and justifications) with merging as is are:

1. Unreleased changes could be bundled in here - I have double checked the commit history and all of the bundled changes are present in prod-stable. So this isn't a concern
2. Weird commit history in main-stable, prod-beta, and prod-stable - this should also be fine because they will all get backfilled to main, and sense we are squashing it will be bundled into one commit anyway

Can I get a +1 from a second set of eyes to make sure I am not missing anything? (cc @cowanrc)

**Comment by cowanrc** [comment]
I don't see anything here that isn't in prod-stable either so I give a +1

**Review by jlgre — APPROVED** [review]
Should be good

**Pull request merged**
