### PR TITLE
fix capitalization errors on pop up

### PR DESCRIPTION
**Pull request by BrooklynLCodes**

### CODE REVIEW

**Comment by jlgre** [comment]
Why is there a submodule added of this repo? Did you accidentally clone the repo inside itself?

**Comment by BrooklynLCodes** [comment]
Hmm strange,  Let me investigate this.

**Comment by jlgre** [comment]
I think there should be a test for this - I am not sure why there wasn't originally but we should add one to cover this pop up

**Comment by jlgre** [comment]
It looks like the "testing added" commit pulled in a bunch of changes from main that shouldn't be in this branch - like removing the title. 

It also still looks like the submodule is present on the changes tab

**Comment by jlgre** [comment]
This looks good except for I still think there should be a test for this function. Not sure if it is testable though. @zanewoodfin can you speak any to the ease of targeting this with a test?

**Comment by BrooklynLCodes** [comment]
Yes I can reach out after I return from lunch.

**Comment by zanewoodfin** [comment]
@jlgre I think it would be a good exercise to try to add unit testing for this "exportManifest" method.  I do not recall if it was an oversight or if it seemed too complicated at the time.  If enough stuff gets stubbed out, it should be doable....

**Review by jlgre — APPROVED** [review]
LGTM!

**Pull request merged**
