### PR TITLE
update docs urls to 2023

### PR DESCRIPTION
**Pull request by ryandeussing**
Where links to Insights, Console, Cost & Subscriptions docs exist, this PR updates the url to the 2023 version

### CODE REVIEW

**Comment by jmbuscemi** [comment]
@ryelo that 2023 is currently 404ing for me. Is there a date when that goes live that we'll neeed to coordinate this release?

**Comment by jmbuscemi** [comment]
@RedHatInsights/teamnado Once this PR is out of `Draft` state, we can release it after the updated 2023 docs are published.

**Comment by ryandeussing** [comment]
@jmbuscemi these 2023 links (I just added another one) won't work until the docs are republished as the new versions.

as noted in Slack, once the new versions are up, redirects will assure that no links to the old versions return a 404.

**Comment by jlgre** [comment]
@ryandeussing is this ready? If so can you remove the `Draft` status so our pipelines can run and this can be reviewed and released?

**Review by jlgre — APPROVED** [review]

**Pull request merged**
